version: '3.9'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - QUEUE_PROVIDER=rabbitmq
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - RABBITMQ_QUEUE=nestjs-queue
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status"]
      interval: 10s
      timeout: 5s
      retries: 5
